In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df1 = pd.read_csv('data1.csv')
df1

,Time_seconds,OmegaX_[deg/s],OmegaY_[deg/s],OmegaZ_[deg/s],AccX_[m/s/s],AccY_[m/s/s],AccZ_[m/s/s],Temperature_[C]
0,0.011,0.000000,0.000000,-0.061035,-0.335303,-0.162861,9.896221,31.64
1,0.022,0.000000,0.000000,-0.061035,-0.354463,-0.162861,9.896221,31.64
2,0.033,0.000000,0.061035,0.000000,-0.349673,-0.153281,9.881850,31.64
3,0.044,0.000000,0.000000,0.000000,-0.383203,-0.172441,9.920171,31.65
4,0.055,0.000000,0.000000,0.000000,-0.387993,-0.177231,9.920171,31.64
...,...,...,...,...,...,...,...,...
2212,24.319,0.000000,0.061035,0.000000,-0.387993,-0.162861,9.901010,31.43
2213,24.330,0.000000,0.000000,0.000000,-0.368833,-0.186811,9.901010,31.43
2214,24.341,0.000000,0.000000,0.000000,-0.344883,-0.182022,9.867480,31.43
2215,24.352,0.061035,0.000000,0.000000,-0.359253,-0.158071,9.929751,31.43
2216,24.363,0.061035,0.000000,0.000000,-0.368833,-0.153281,9.886641,31.42

In [4]:
df1['static_bias_X'] = df1['OmegaX_[deg/s]'].mean()
df1['static_bias_Y'] = df1['OmegaY_[deg/s]'].mean()
df1['static_bias_Z'] = df1['OmegaZ_[deg/s]'].mean()

df1['static_acc_X'] = df1['AccX_[m/s/s]'].mean()
df1['static_acc_Y'] = df1['AccY_[m/s/s]'].mean() + 1.1
df1['static_acc_Z'] = df1['AccZ_[m/s/s]'].mean() - 9.81

df1

,Time_seconds,OmegaX_[deg/s],OmegaY_[deg/s],OmegaZ_[deg/s],AccX_[m/s/s],AccY_[m/s/s],AccZ_[m/s/s],Temperature_[C],static_bias_X,static_bias_Y,static_bias_Z,static_acc_X,static_acc_Y,static_acc_Z
0,0.011,0.000000,0.000000,-0.061035,-0.335303,-0.162861,9.896221,31.64,0.000496,0.017454,-0.01561,-0.361424,0.929341,0.074582
1,0.022,0.000000,0.000000,-0.061035,-0.354463,-0.162861,9.896221,31.64,0.000496,0.017454,-0.01561,-0.361424,0.929341,0.074582
2,0.033,0.000000,0.061035,0.000000,-0.349673,-0.153281,9.881850,31.64,0.000496,0.017454,-0.01561,-0.361424,0.929341,0.074582
3,0.044,0.000000,0.000000,0.000000,-0.383203,-0.172441,9.920171,31.65,0.000496,0.017454,-0.01561,-0.361424,0.929341,0.074582
4,0.055,0.000000,0.000000,0.000000,-0.387993,-0.177231,9.920171,31.64,0.000496,0.017454,-0.01561,-0.361424,0.929341,0.074582
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2212,24.319,0.000000,0.061035,0.000000,-0.387993,-0.162861,9.901010,31.43,0.000496,0.017454,-0.01561,-0.361424,0.929341,0.074582
2213,24.330,0.000000,0.000000,0.000000,-0.368833,-0.186811,9.901010,31.43,0.000496,0.017454,-0.01561,-0.361424,0.929341,0.074582
2214,24.341,0.000000,0.000000,0.000000,-0.344883,-0.182022,9.867480,31.43,0.000496,0.017454,-0.01561,-0.361424,0.929341,0.074582
2215,24.352,0.061035,0.000000,0.000000,-0.359253,-0.158071,9.929751,31.43,0.000496,0.017454,-0.01561,-0.361424,0.929341,0.074582
2216,24.363,0.061035,0.000000,0.000000,-0.368833,-0.153281,9.886641,31.42,0.000496,0.017454,-0.01561,-0.361424,0.929341,0.074582

In [5]:
df2 = pd.read_csv('data2.csv')
df2

,Time_seconds,OmegaX_[deg/s],OmegaY_[deg/s],OmegaZ_[deg/s],AccX_[m/s/s],AccY_[m/s/s],AccZ_[m/s/s],Temperature_[C]
0,0.011,0.0,0.000000,0.0,-0.344883,-0.167651,9.872271,31.41
1,0.022,0.0,0.000000,0.0,-0.335303,-0.143701,9.881850,31.42
2,0.033,0.0,0.000000,0.0,-0.349673,-0.148491,9.896221,31.43
3,0.044,0.0,0.000000,0.0,-0.378413,-0.167651,9.881850,31.43
4,0.055,0.0,0.000000,0.0,-0.373623,-0.191602,9.886641,31.44
...,...,...,...,...,...,...,...,...
2270,24.956,0.0,0.000000,0.0,-0.364043,-0.167651,9.910591,31.37
2271,24.967,0.0,0.000000,0.0,-0.354463,-0.177231,9.896221,31.37
2272,24.978,0.0,0.061035,0.0,-0.359253,-0.177231,9.872271,31.37
2273,24.989,0.0,0.061035,0.0,-0.364043,-0.172441,9.920171,31.37
2274,25.000,0.0,0.000000,0.0,-0.373623,-0.191602,9.915380,31.38

In [84]:
df2['static_bias_X'] = df2['OmegaX_[deg/s]'].mean()
df2['static_bias_Y'] = df2['OmegaY_[deg/s]'].mean()
df2['static_bias_Z'] = df2['OmegaZ_[deg/s]'].mean()

df2['static_acc_X'] = df2['AccX_[m/s/s]'].mean()
df2['static_acc_Y'] = df2['AccY_[m/s/s]'].mean() + 1.1
df2['static_acc_Z'] = df2['AccZ_[m/s/s]'].mean() - 9.81

df2

,Time_seconds,OmegaX_[deg/s],OmegaY_[deg/s],OmegaZ_[deg/s],AccX_[m/s/s],AccY_[m/s/s],AccZ_[m/s/s],Temperature_[C],static_bias_X,static_bias_Y,static_bias_Z,static_acc_X,static_acc_Y,static_acc_Z
0,0.011,0.0,0.000000,0.0,-0.344883,-0.167651,9.872271,31.41,0.004051,0.013924,-0.010624,-0.362329,0.929837,0.076401
1,0.022,0.0,0.000000,0.0,-0.335303,-0.143701,9.881850,31.42,0.004051,0.013924,-0.010624,-0.362329,0.929837,0.076401
2,0.033,0.0,0.000000,0.0,-0.349673,-0.148491,9.896221,31.43,0.004051,0.013924,-0.010624,-0.362329,0.929837,0.076401
3,0.044,0.0,0.000000,0.0,-0.378413,-0.167651,9.881850,31.43,0.004051,0.013924,-0.010624,-0.362329,0.929837,0.076401
4,0.055,0.0,0.000000,0.0,-0.373623,-0.191602,9.886641,31.44,0.004051,0.013924,-0.010624,-0.362329,0.929837,0.076401
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2270,24.956,0.0,0.000000,0.0,-0.364043,-0.167651,9.910591,31.37,0.004051,0.013924,-0.010624,-0.362329,0.929837,0.076401
2271,24.967,0.0,0.000000,0.0,-0.354463,-0.177231,9.896221,31.37,0.004051,0.013924,-0.010624,-0.362329,0.929837,0.076401
2272,24.978,0.0,0.061035,0.0,-0.359253,-0.177231,9.872271,31.37,0.004051,0.013924,-0.010624,-0.362329,0.929837,0.076401
2273,24.989,0.0,0.061035,0.0,-0.364043,-0.172441,9.920171,31.37,0.004051,0.013924,-0.010624,-0.362329,0.929837,0.076401
2274,25.000,0.0,0.000000,0.0,-0.373623,-0.191602,9.915380,31.38,0.004051,0.013924,-0.010624,-0.362329,0.929837,0.076401

In [85]:
df3 = pd.read_csv('data3.csv')
df3

,Time_seconds,OmegaX_[deg/s],OmegaY_[deg/s],OmegaZ_[deg/s],AccX_[m/s/s],AccY_[m/s/s],AccZ_[m/s/s],Temperature_[C]
0,0.011,0.000000,0.000000,0.0,-0.364043,-0.162861,9.881850,31.37
1,0.022,0.000000,0.061035,0.0,-0.383203,-0.177231,9.857901,31.37
2,0.033,-0.061035,0.000000,0.0,-0.383203,-0.182022,9.886641,31.36
3,0.044,0.000000,0.000000,0.0,-0.359253,-0.162861,9.901010,31.36
4,0.055,0.000000,0.061035,0.0,-0.349673,-0.182022,9.901010,31.36
...,...,...,...,...,...,...,...,...
2361,25.956,0.000000,0.000000,0.0,-0.354463,-0.148491,9.886641,31.30
2362,25.967,0.000000,-0.061035,0.0,-0.368833,-0.158071,9.886641,31.32
2363,25.978,0.000000,-0.061035,0.0,-0.359253,-0.158071,9.896221,31.32
2364,25.989,0.000000,0.000000,0.0,-0.359253,-0.162861,9.891431,31.31
2365,26.000,0.000000,0.000000,0.0,-0.368833,-0.153281,9.891431,31.31

In [86]:
df3['static_bias_X'] = df3['OmegaX_[deg/s]'].mean()
df3['static_bias_Y'] = df3['OmegaY_[deg/s]'].mean()
df3['static_bias_Z'] = df3['OmegaZ_[deg/s]'].mean()

df3['static_acc_X'] = df3['AccX_[m/s/s]'].mean()
df3['static_acc_Y'] = df3['AccY_[m/s/s]'].mean() + .1
df3['static_acc_Z'] = df3['AccZ_[m/s/s]'].mean() - 9.81

df3

,Time_seconds,OmegaX_[deg/s],OmegaY_[deg/s],OmegaZ_[deg/s],AccX_[m/s/s],AccY_[m/s/s],AccZ_[m/s/s],Temperature_[C],static_bias_X,static_bias_Y,static_bias_Z,static_acc_X,static_acc_Y,static_acc_Z
0,0.011,0.000000,0.000000,0.0,-0.364043,-0.162861,9.881850,31.37,0.004127,0.012408,-0.007713,-0.363492,-0.069686,0.076926
1,0.022,0.000000,0.061035,0.0,-0.383203,-0.177231,9.857901,31.37,0.004127,0.012408,-0.007713,-0.363492,-0.069686,0.076926
2,0.033,-0.061035,0.000000,0.0,-0.383203,-0.182022,9.886641,31.36,0.004127,0.012408,-0.007713,-0.363492,-0.069686,0.076926
3,0.044,0.000000,0.000000,0.0,-0.359253,-0.162861,9.901010,31.36,0.004127,0.012408,-0.007713,-0.363492,-0.069686,0.076926
4,0.055,0.000000,0.061035,0.0,-0.349673,-0.182022,9.901010,31.36,0.004127,0.012408,-0.007713,-0.363492,-0.069686,0.076926
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2361,25.956,0.000000,0.000000,0.0,-0.354463,-0.148491,9.886641,31.30,0.004127,0.012408,-0.007713,-0.363492,-0.069686,0.076926
2362,25.967,0.000000,-0.061035,0.0,-0.368833,-0.158071,9.886641,31.32,0.004127,0.012408,-0.007713,-0.363492,-0.069686,0.076926
2363,25.978,0.000000,-0.061035,0.0,-0.359253,-0.158071,9.896221,31.32,0.004127,0.012408,-0.007713,-0.363492,-0.069686,0.076926
2364,25.989,0.000000,0.000000,0.0,-0.359253,-0.162861,9.891431,31.31,0.004127,0.012408,-0.007713,-0.363492,-0.069686,0.076926
2365,26.000,0.000000,0.000000,0.0,-0.368833,-0.153281,9.891431,31.31,0.004127,0.012408,-0.007713,-0.363492,-0.069686,0.076926

In [87]:
df_full = pd.read_csv('data4.csv')
df_full

,Time_seconds,OmegaX_[deg/s],OmegaY_[deg/s],OmegaZ_[deg/s],AccX_[m/s/s],AccY_[m/s/s],AccZ_[m/s/s],Temperature_[C]
0,0.011,0.000000,0.000000,0.0,-0.364043,-0.162861,9.881850,31.37
1,0.022,0.000000,0.061035,0.0,-0.383203,-0.177231,9.857901,31.37
2,0.033,-0.061035,0.000000,0.0,-0.383203,-0.182022,9.886641,31.36
3,0.044,0.000000,0.000000,0.0,-0.359253,-0.162861,9.901010,31.36
4,0.055,0.000000,0.061035,0.0,-0.349673,-0.182022,9.901010,31.36
...,...,...,...,...,...,...,...,...
6853,24.319,0.000000,0.061035,0.0,-0.387993,-0.162861,9.901010,31.43
6854,24.330,0.000000,0.000000,0.0,-0.368833,-0.186811,9.901010,31.43
6855,24.341,0.000000,0.000000,0.0,-0.344883,-0.182022,9.867480,31.43
6856,24.352,0.061035,0.000000,0.0,-0.359253,-0.158071,9.929751,31.43
6857,24.363,0.061035,0.000000,0.0,-0.368833,-0.153281,9.886641,31.42

In [507]:
staticX = (df1.static_bias_X[0] + df2.static_bias_X[0] + df3.static_bias_X[0]) / 3
staticY = (df1.static_bias_Y[0] + df2.static_bias_Y[0] + df3.static_bias_Y[0]) / 3
staticZ = (df1.static_bias_Z[0] + df2.static_bias_Z[0] + df3.static_bias_Z[0]) / 3

r2rX = np.ptp([df1.static_bias_X[0], df2.static_bias_X[0], df3.static_bias_X[0]])
r2rY = np.ptp([df1.static_bias_Y[0], df2.static_bias_Y[0], df3.static_bias_Y[0]])
r2rZ = np.ptp([df1.static_bias_Z[0], df2.static_bias_Z[0], df3.static_bias_Z[0]])

inrX = np.sqrt(np.mean((df_full['OmegaX_[deg/s]'])-staticX)**2)
inrY = np.sqrt(np.mean((df_full['OmegaY_[deg/s]'])-staticY)**2) 
inrZ = np.sqrt(np.mean((df_full['OmegaZ_[deg/s]'])-staticZ)**2)

staticXa = (df1.static_acc_X[0] + df2.static_acc_X[0] + df3.static_acc_X[0]) / 3
staticYa = (df1.static_acc_Y[0] + df2.static_acc_Y[0] + df3.static_acc_Y[0]) / 3
staticZa = (df1.static_acc_Z[0] + df2.static_acc_Z[0] + df3.static_acc_Z[0]) / 3

r2rXa = max(df1.static_acc_X[0], df2.static_acc_X[0],  df3.static_acc_X[0]) - min(df1.static_acc_X[0], df2.static_acc_X[0],  df3.static_acc_X[0])
r2rYa = max(df1.static_acc_Y[0], df2.static_acc_Y[0],  df3.static_acc_Y[0]) - min(df1.static_acc_Y[0], df2.static_acc_Y[0],  df3.static_acc_Y[0])
r2rZa = max(df1.static_acc_Z[0], df2.static_acc_Z[0],  df3.static_acc_Z[0]) - min(df1.static_acc_Z[0], df2.static_acc_Z[0],  df3.static_acc_Z[0])

inrXa = np.sqrt(np.mean(sum(df_full['AccX_[m/s/s]'])-staticX)**2) / len(df_full)
inrYa = np.sqrt(np.mean(sum(df_full['AccY_[m/s/s]'])-staticY)**2) / len(df_full)
inrZa = np.sqrt(np.mean(sum(df_full['AccZ_[m/s/s]'])-staticZ)**2) / len(df_full)


data = pd.DataFrame({'Static': [staticX, staticY, staticZ,staticXa, staticYa, staticZa] , 'R2R' : [r2rX, r2rY, r2rZ,r2rXa, r2rYa, r2rZa], 'InRun' : [inrX, inrY, (inrZ),inrXa, inrYa , (inrZa- 9.81)]})
data

     Static       R2R     InRun
0  0.002891  0.003632  0.002928
1  0.014596  0.005046  0.014540
2 -0.011316  0.007897  0.011230
3 -0.362415  0.002068  0.362438
4  0.596497  0.999523  0.170161
5  0.075969  0.002345  0.075996

In [13]:
print("Spam & Eggs")

Spam & Eggs